title: Johannes Mayrhofer, an International Student
author:
  name: Johannes Mayrhofer
  email: MayrhoferJJ@hendrix.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Hello, this is my personal blog, I am an international student from Austria. It is 
  my first time in the US and i am looking forward to learning both professionally and on 
  a human level.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
     - { platform: facebook,       user_url: "https://www.facebook.com/hendrixcollege/" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
